import { aartiChaturvedi, akshiPatel, anahitaPatel, anitaNayka, bhumiSolanki, bishnupriyaDas, dimpalRavat, jalpaPatel, jhanviChauhan, jignaSolanki, kajalPatel, kaminiPatel, nehalBarot, payalNayka, shitalPatel, sunitabenPatel, swetaRathod, varshaGoswami, varshikaPatel } from "../assets/staff"

export interface StaffMember {
    imageUrl: string,
    name: string,
    designation: string,
    qualification: string,
    experience: string
}

export const StaffDetails: StaffMember[] = [
    {
        imageUrl: aartiChaturvedi,
        name: "Aarti Chaturvedi",
        designation: "Principal",
        qualification: "M.A., M. Ed",
        experience: "17 years",
    },
    {
        imageUrl: nehalBarot,
        name: "Neha Barot",
        designation: "Vice Principal",
        qualification: "B. Com, B. Ed, M. Com(pursuing)",
        experience: "16 years",
    },
    {
        imageUrl: jalpaPatel,
        name: "Jalpa Patel",
        designation: "Clerical cum Teacher",
        qualification: "B. Com, Montessori",
        experience: "10 years",
    },
    {
        imageUrl: varshaGoswami,
        name: "Varsha Goswami",
        designation: "Co-Curricular Activity Co-ordinator",
        qualification: "D.El.Ed",
        experience: "16 years",
    },
    {
        imageUrl: dimpalRavat,
        name: "Dimpal Ravat",
        designation: "Ass. Teacher",
        qualification: "P.T.C., B.A., E.Ed",
        experience: "10 years",
    },
    {
        imageUrl: kaminiPatel,
        name: "Kamini Patel",
        designation: "Ass. Teacher",
        qualification: "M.A., E.Ed",
        experience: "12 years",
    },
    {
        imageUrl: kajalPatel,
        name: "Kajal Patel",
        designation: "Lab. Incharge, Ass. Teacher",
        qualification: "B.Sc, B.Ed",
        experience: "3 years",
    },
    {
        imageUrl: swetaRathod,
        name: "Sweta Rathod",
        designation: "Ass. Teacher",
        qualification: "M.Sc, B.Ed",
        experience: "2.5 years",
    },
    {
        imageUrl: akshiPatel,
        name: "Akshi Patel",
        designation: "Ass. Teacher",
        qualification: "M.Sc, B.Ed",
        experience: "1.5 years",
    },
    {
        imageUrl: jhanviChauhan,
        name: "Jhanvi Chauhan",
        designation: "Ass. Teacher",
        qualification: "B.A., B.Ed, A.T.D, COPA",
        experience: "2 years",
    },
    {
        imageUrl: bishnupriyaDas,
        name: "Bishnupriya Das",
        designation: "Ass. Teacher",
        qualification: "M.A., B.Ed",
        experience: "8 years",
    },
    {
        imageUrl: shitalPatel,
        name: "Shital Patel",
        designation: "Ass. Teacher",
        qualification: "M.Sc., M.Ed",
        experience: "1.5 years",
    },
    {
        imageUrl: bhumiSolanki,
        name: "Bhumi Solanki",
        designation: "Ass. Teacher",
        qualification: "M.Sc., M.Ed",
        experience: "1 years",
    },
    {
        imageUrl: jignaSolanki,
        name: "Jigna Solanki",
        designation: "Ass. Teacher",
        qualification: "M.A, B.Ed",
        experience: "8 years",
    },
    {
        imageUrl: anahitaPatel,
        name: "Anahita Patel",
        designation: "Primary Co-ordinator",
        qualification: "B.A, D.El.ed (Pursuing M.A , B.Ed)",
        experience: "17 years",
    },
    {
        imageUrl: sunitabenPatel,
        name: "Sunitaben Patel",
        designation: "Peon",
        qualification: "10th pass",
        experience: "4 years",
    },
    {
        imageUrl: varshikaPatel,
        name: "Varshika Patel",
        designation: "Peon",
        qualification: "S.Y, B. Com",
        experience: "3 years",
    },
    {
        imageUrl: payalNayka,
        name: "Payal Nayka",
        designation: "Peon",
        qualification: "9th pass",
        experience: "3 years",
    },
    {
        imageUrl: anitaNayka,
        name: "Anita Nayka",
        designation: "Peon",
        qualification: "9th pass",
        experience: "3 years",
    },
]
